config:
    fps: 100
    max_frame_time: 0.1
    num_fps_avg: 1000
    render_decision_trees: True
    scroll_width_x: 30
    scroll_width_y: 25
    state_id: "-{0}"
    view_x: 60
    view_y: 50
    window_title: "Fantasy-RTS (FPS: {0:.0f})"
    
    keys:
        - action: action.cursor_north
          key: UP
        - action: action.cursor_south
          key: DOWN
        - action: action.cursor_west
          key: LEFT
        - action: action.cursor_east
          key: RIGHT
        - action: action.scroll_north
          key: W
        - action: action.scroll_south
          key: S
        - action: action.scroll_west
          key: A
        - action: action.scroll_east
          key: D
        - action: action.scroll_up
          key: R
        - action: action.scroll_down
          key: Q